wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1657405680
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      4: 3.10.4
      5: 0.12.21
      8:
      - 1
      - 5
